# Generated by Django 6.0.5 on 2026-06-13 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimelinePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('intro_text', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TimelineYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='timeline.timelinepage')),
            ],
            options={
                'ordering': ['sort_order', 'year'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('date_label', models.CharField(blank=True, help_text='Например: FEB 28. Если оставить пустым, подпись будет собрана из даты.', max_length=50)),
                ('kicker', models.CharField(blank=True, help_text='Короткая строка над заголовком.', max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='timeline/events/%Y/%m/')),
                ('image_alt', models.CharField(blank=True, max_length=250)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='timeline.timelineyear')),
            ],
            options={
                'ordering': ['sort_order', 'event_date', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='timelineyear',
            constraint=models.UniqueConstraint(fields=('page', 'year'), name='unique_timeline_year_per_page'),
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['year', 'event_date'], name='timeline_ti_year_id_01b0d6_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['year', 'sort_order'], name='timeline_ti_year_id_3fdbbe_idx'),
        ),
    ]
