# Generated by Django 6.0.5 on 2026-06-14 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_simplify_timeline_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeline',
            options={'ordering': ['name'], 'verbose_name': 'Таймлайн', 'verbose_name_plural': 'Таймлайны'},
        ),
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['event_date', 'id'], 'verbose_name': 'Событие таймлайна', 'verbose_name_plural': 'События таймлайна'},
        ),
        migrations.AlterField(
            model_name='timeline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='description',
            field=models.TextField(blank=True, help_text='Внутреннее описание таймлайна для администраторов.', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Если выключено, публичная страница таймлайна будет недоступна.', verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='name',
            field=models.CharField(help_text='Используется в адресе страницы, например demo или vpro. Лучше использовать латиницу, цифры и дефисы.', max_length=120, unique=True, verbose_name='Техническое имя'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, который отвечает за этот таймлайн.', on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='description',
            field=models.TextField(blank=True, help_text='Текст события, который будет показан под заголовком.', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='event_date',
            field=models.DateField(help_text='Используется для сортировки, группировки по годам и автоматических подписей на публичной странице.', verbose_name='Дата события'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='image',
            field=models.ImageField(blank=True, help_text='Фоновое изображение события. Рекомендуется горизонтальное изображение хорошего качества.', upload_to='timeline/events/%Y/%m/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Если выключено, событие не будет отображаться на публичной странице.', verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='timeline',
            field=models.ForeignKey(help_text='Таймлайн, к которому относится событие.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='timeline.timeline', verbose_name='Таймлайн'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='title',
            field=models.CharField(help_text='Основной заголовок события на публичной странице.', max_length=250, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
