# Generated by Django 6.0.5 on 2026-07-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_alter_timeline_options_alter_timelineevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='owner_only',
            field=models.BooleanField(default=False, help_text='Если включено, публичную страницу сможет открыть только авторизованный владелец таймлайна или администратор.', verbose_name='Просмотр только для владельца'),
        ),
    ]
