# Generated by Django 6.0.5 on 2026-05-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
