# Generated by Django 6.0.5 on 2026-07-26 13:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_plant_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('watering', 'Полив'), ('inspection', 'Осмотр'), ('treatment', 'Лечение'), ('soil_change', 'Смена грунта'), ('note', 'Заметка'), ('fertilizing', 'Внесение удобрения'), ('other', 'Другое')], max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=150)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='garden.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['user', 'plant', '-occurred_at'], name='garden_plan_user_id_b8b43d_idx'), models.Index(fields=['plant', 'event_type', '-occurred_at'], name='garden_plan_plant_i_d84dca_idx')],
            },
        ),
    ]
