# Generated by Django 6.0.5 on 2026-06-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('ares_local', 'Локальный файл на ares')], default='ares_local', max_length=32)),
                ('file_path', models.CharField(max_length=1024)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField()),
                ('modified_at', models.DateTimeField()),
                ('fingerprint', models.CharField(max_length=512, unique=True)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('processing', 'В обработке'), ('completed', 'Завершено'), ('failed', 'Ошибка')], db_index=True, default='queued', max_length=32)),
                ('locked_by', models.CharField(blank=True, max_length=255)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('process_instance_key', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('transcript_path', models.CharField(blank=True, max_length=1024)),
                ('language', models.CharField(blank=True, max_length=32)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_type', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='transcripti_status_93d188_idx')],
            },
        ),
    ]
