# Generated by Django 6.0.5 on 2026-06-06 10:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garden', '0003_plant_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantSoil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('set_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_current', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soils', to='garden.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_soils', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-set_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoilComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_components', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlantSoilComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100)])),
                ('plant_soil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='soil.plantsoil')),
                ('soil_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plant_soil_parts', to='soil.soilcomponent')),
            ],
            options={
                'ordering': ['soil_component__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='plantsoil',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('plant',), name='unique_current_soil_per_plant'),
        ),
        migrations.AddConstraint(
            model_name='soilcomponent',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_soil_component_per_user'),
        ),
        migrations.AddConstraint(
            model_name='plantsoilcomponent',
            constraint=models.UniqueConstraint(fields=('plant_soil', 'soil_component'), name='unique_component_per_plant_soil'),
        ),
    ]
